language: node_js

node_js:
  - 'node' # ensure we're always testing on the latest version of Node.js
  - '6'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms:
      - secure: NGn87q+6FfLVKwuC0j0IbqT5uJgZUTEiSZwSMzZnVpnI0f27sT4cRQDEJpfKge9GJoMyPUNR8rfYJVX5zSLEV+jXV6sCxnQO3PDNSPJyvBjQuuiNF/ZNItEc+TEg3QCiv2s9PjcVQfc2r7F6+tVG5Ce+vfTpsgRZplfAG3PAYtSePHUTbWhDvARq5eTMW++P1oqaxhL0KxGuQMKBqjU2S+LAt1ky7UdhZqu6+6LY1oaaTDjl8Yvn/GdRklD39aWW6vx2Z2kvuFW2Stq9vtQ0GFZdt8ttTbn2l8nwAuOluIFvseooTtClDfcVDutQD42TD5/pRGjSHSaNmGbMCEcMKxQ55e4gY5KUkWdEMXIq0u9gr5xQa63pq/tQoSni/9YOs4jtFLYYU0ZWr6zY6cpqka7q8uxE22P61abLTIlEbSGatNsTgKoX5Upnj2U/L8BKbcWG4YHwXdlG6F7qyMIxTArYd9aja3nTLgXzwhT2f0WgwwB+vDv5LoQHNm2H2VXrS4rwQ5lhD5DGzFvQFl8WS+p7EHLibHN2s+ZiU8k+LvVN88THDlun+G5jVAoJAkg83OVguU284BZC+6kHbxMtjMm3T9lgAAXp+mcWaL0Jopm+JTlRvnT5hKyJVklKtWB0Gn4ox73qsSAc7OrX2P7ZrZ6ztITWNA6LdPquQVYZBYA=
    on_success: change
    on_failure: always

deploy:
  provider: npm
  email: "mahnkem@msoe.edu"
  api_key:
    secure: "Sp+qlImWLzoLX22oB6AJb3vNqoeqrLVAAzuXGpdm7+UdR7tsApNuCF1RBo0TmXlMyIwmbpKF9EjAXmtwMWMwT0aP3crryo3njeWe5Ri3pUSznAWY3qCceBZlqkHuwctOL7NdRRMp5ny7wraW3GTIFiVj5eZAsni4ruL+fjIzZ4HclbuwUYWdEqWKYvm9JYvJB2eyCOOqZ5PgffMlKN3rjW2soW6LIiOAe40OFuc9t0Y3/CJUprD+6eM2E8slzHBpDHwA1sMz6EYBqvJDjo+006AyXNC2FdyJcJVXd83rMKjHxYMd0Slem0cQptzoFbKhRChAQcSYmO49N2oJIs3u3LqJd+B7mpXmBXQPJ/uNO5xEvFMAiheDvmNvIRlFzFcXH9FKgLpfLsTkU57y5QCV0yZOnGIBPmpBh+ymyA+F3dKTStBJ7H1Yu9u8/nJRzR3vnpmv3jfgKtLbPnQGz+Vz+/CayR9NUM2mhqar1TIeNQcEsRiQlfJMN4ZhmuFw5571OWZi9t7RhA9fBjSuw/grpIGBVj/eCGFgtxut/xfEOcubZmLl2BaSam6RDvXE1JIyuYisJAg97gddHtv75OH87a+cWkhm286wYfatSyIrv7NbwqrRGOg8MwoP7OZvcrJUTwqCGuMlU2FFGPdaqlr7MkjQMW8+7CcEKuhyfZagKh8="
  on:
    tags: true
    node: '6'
